# HTMLProofer configuration for GitHub Pages deployment
# Ignore the empty href issue that occurs with Chirpy theme
ignore_empty_alt: true
ignore_missing_alt: true
ignore_status_codes: [0, 500, 999]
ignore_urls:
  - ""
  - "#"
  - !ruby/regexp '/\/_posts\/attachments\/.*/'
enforce_https: false
check_external_hash: false
check_internal_hash: false
swap_urls:
  "^http://": "https://"